USE wp_user;

insert into state
(state_id, state_name)
values
("AL", "Alabama"),
("AK", "Alaska"),
("AS", "American Samoa"),
("AZ", "Arizona"),
("AR", "Arkansas"),
("CA", "California"),
("CO", "Colorado"),
("CT", "Connecticut"),
("DE", "Delaware"),
("DC", "District Of Columbia"),
("FM", "Federated States Of Micronesia"),
("FL", "Florida"),
("GA", "Georgia"),
("GU", "Guam"),
("HI", "Hawaii"),
("ID", "Idaho"),
("IL", "Illinois"),
("IN", "Indiana"),
("IA", "Iowa"),
("KS", "Kansas"),
("KY", "Kentucky"),
("LA", "Louisiana"),
("ME", "Maine"),
("MH", "Marshall Islands"),
("MD", "Maryland"),
("MA", "Massachusetts"),
("MI", "Michigan"),
("MN", "Minnesota"),
("MS", "Mississippi"),
("MO", "Missouri"),
("MT", "Montana"),
("NE", "Nebraska"),
("NV", "Nevada"),
("NH", "New Hampshire"),
("NJ", "New Jersey"),
("NM", "New Mexico"),
("NY", "New York"),
("NC", "North Carolina"),
("ND", "North Dakota"),
("MP", "Northern Mariana Islands"),
("OH", "Ohio"),
("OK", "Oklahoma"),
("OR", "Oregon"),
("PW", "Palau"),
("PA", "Pennsylvania"),
("PR", "Puerto Rico"),
("RI", "Rhode Island"),
("SC", "South Carolina"),
("SD", "South Dakota"),
("TN", "Tennessee"),
("TX", "Texas"),
("UT", "Utah"),
("VT", "Vermont"),
("VI", "Virgin Islands"),
("VA", "Virginia"),
("WA", "Washington"),
("WV", "West Virginia"),
("WI", "Wisconsin"),
("WY", "Wyoming");


insert into new_user
(user_fname, user_lname, user_phone, user_address, user_email, city,zip,state_id)
values
("Colly", "Clift", "4066653305","356 Alphabet Dr", "CollyVClift@gmail.com", "Nashua", "03060", "NH"),
("Trina", "Jaclyn", "4066253436","425 4th Ave W", "TrinaBJaclyn@gmail.com", "Friendswood", "77546", "TX"),
("Gwendolyn", "Janela", "4064404606","631 Meridian Road", "GwendolynWJanela@gmail.com", "Macon", "31204", "GA"),
("Edith", "Cosme", "4065406455","125 Swerve Street", "EdithECosme@gmail.com", "Bozeman", "59715", "MT"),
("Timi", "Airlie", "4061641115","753 Rundown Dr", "TimiDAirlie@gmail.com", "Denver", "80202", "CO"),
("Jillian", "Wetzel", "4064513232","367 TurnCorner Ave", "JillianRWetzel@gmail.com", "Franklin", "37064",  "TN"),
("Riki", "Marras", "4065545035","981 RunRed Street", "RikiEMarras@gmail.com", "Charleston", "25301", "WV"),
("Rosabella", "Chretien", "4063234226","186 Jump Street", "RosabellaBChretien@gmail.com", "Harrisonburg", "22801", "VA"),
("Ursala", "Cardinal", "4062056245","987 Calabrim Highway", "UrsalaDCardinal@gmail.com", "Ocoee", "34761", "FL"),
("Cilka", "Carolin", "4063124610","782 TooLate Ave NW", "CilkaBCarolin@gmail.com", "New Berlin", "53146", "WI"),
("Karel", "Lucier", "4062350122","983 Factory Way", "KarelTLucier@gmail.com", "Anchorage", "99501", "AK"),
("Athena", "Tori", "4065425303","245 Left Dr", "AthenaGTori@gmail.com", "Thornton", "80229", "CO"),
("Rene", "Higinbotham", "4063430414","573 Boxed In Street", "ReneKHiginbotham@gmail.com", "Wilmington", "19801", "DE"),
("Darice", "Stine", "4061114016","821 Street Way", "DariceMStine@gmail.com", "Annapolis", "21403", "MD");